/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export const recommended = {
  rules: {
    'ajel/ajel-disable-throw': 'warn',
    'ajel/ajel-disable-try-catch': 'error',
    'ajel/ajel-require-error-handling': 'error',
  },
};
