/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import ajelConstTuples from './rules/ajel-const-tuples';
import ajelDisableThrow from './rules/ajel-disable-throw';
import ajelDisableTryCatch from './rules/ajel-disable-try-catch';
import ajelRequireTupleDeclaration from './rules/ajel-require-tuple-declaration';
import ajelStrictErrorInstanceof from './rules/ajel-strict-error-instanceof';
import ajelRequireErrorHandling from './rules/ajel-require-error-handling';
import sjelRequireCurrying from './rules/sjel-require-currying';

export const configs = {
  recommended,
};

export const rules = {
  'ajel-const-tuples': ajelConstTuples,
  'ajel-disable-throw': ajelDisableThrow,
  'ajel-disable-try-catch': ajelDisableTryCatch,
  'ajel-require-tuple-declaration': ajelRequireTupleDeclaration,
  'ajel-strict-error-instanceof': ajelStrictErrorInstanceof,
  'ajel-require-error-handling': ajelRequireErrorHandling,
  'sjel-require-currying': sjelRequireCurrying,
};
