/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import ajelDisableThrow from './rules/ajel-disable-throw';
import ajelDisableTryCatch from './rules/ajel-disable-try-catch';
import ajelRequireErrorHandling from './rules/ajel-require-error-handling';

export const configs = {
  recommended,
};

export const rules = {
  'ajel-disable-throw': ajelDisableThrow,
  'ajel-disable-try-catch': ajelDisableTryCatch,
  'ajel-require-error-handling': ajelRequireErrorHandling,
};
